### ISSUE TITLE
Replace lodash with lodash.isequal

### ISSUE THREAD

**Issue by GnomedDev** [VaguelySerious/react-quill#23]
It looks like the entire, non-tree-shakable version of lodash is being included in order to use the single `isEqual` function. Could this be replaced to cut down on bundle sizes, or lodash be replaced with lodash-es to get this tree-shaking automatically?

**Comment by VaguelySerious** [comment]
Thank you for your suggestion! We just released package version 3.4.0 which uses `lodash-es` and should address this issue

**Comment by GnomedDev** [comment]
Cool, this cut down on around 35kb (gzipped) of bundle size, but it seems like `rollup-plugin-visualizer` is still showing 44kb (gzipped) of non-tree-shaken lodash-es, alongside the `lodash.clonedeep` and `lodash.isequal` libraries? Can you do anything about that?

**Comment by VaguelySerious** [comment]
@GnomedDev Note that the underlying Quill library also uses `lodash-es` and might be bundling that in a way that's not tree-shakable, which I suspect I can't do much about, though if you do spot someting this package could be doing better, please let me know.

If you're concerned about your project's bundle size, I recommend lazy loading the component that uses `ReactQuill`, e.g. via `React.lazy` if your bundler supports it.

**Comment by GnomedDev** [comment]
Okay, I'll open an issue on the Quill library to get this sorted then. 

I am lazy loading it already, which helps reduce the initial load hit, but this seems like a silly problem to have in the first place hence opening this issue to get it fixed. 

Thanks a ton for the help and maintaining this fork!

**Comment by VaguelySerious** [comment]
Thank you! Cheers
