### ISSUE TITLE
New version 3.4.1 duplicate toolbar

### ISSUE THREAD

**Issue by Noah-mh** [VaguelySerious/react-quill#27]
the tool bar is being duplicated in the new version 3.4.1

**Comment by VaguelySerious** [comment]
Makes sense given the changes made, but I still can't seem to replicate this. Could you share the code you're using?

Alternative, could you [fork this code sandbox](https://codesandbox.io/p/sandbox/reactquillnew-test-forked-4tyl78?file=%2Fsrc%2Findex.jsx%3A6%2C23) and make the necessary changes?

**Comment by Noah-mh** [comment]
this is how i am using in my nextjs app, 

it was fine on 3.3.3, 
i didnt upgrade to 3.4.0 tho, 

```
"use client";

import React from "react";
import dynamic from "next/dynamic";
import "react-quill-new/dist/quill.snow.css";

import { cn } from "@/lib/utils";
const ReactQuill = dynamic(() => import("react-quill-new"), { ssr: false });

const modules = {
  toolbar: [
    [{ header: [1, 2, 3, false] }],
    ["bold", "italic"],
    [{ list: "ordered" }, { list: "bullet" }],
    ["clean"],
  ],
};

const formats = ["header", "bold", "italic", "list"];

interface MarkdownEditorProps {
  value: string;
  onChange: (value: string) => void;
  className?: string;
}

const MarkdownEditor: React.FC<MarkdownEditorProps> = ({
  value,
  onChange,
  className,
}) => {
  return (
    <div className={cn("prose dark:prose-invert rounded-md", className)}>
      <ReactQuill
        theme="snow"
        value={value}
        onChange={onChange}
        modules={modules}
        formats={formats}
        className="border-input bg-background relative w-full"
        style={{ zIndex: 1 }}
      />
    </div>
  );
};

export default MarkdownEditor;

```

**Comment by VaguelySerious** [comment]
@Noah-mh I pasted your code into [this sandbox](https://codesandbox.io/p/devbox/reactquillnew-test-forked-s6cyw3?workspaceId=ws_QDGSEW3FfYAFd7W4RjCofB), and it seems to work fine. Anything I'm missing?

**Comment by tanujayawilhelmus** [comment]
I copied the code from sandbox to my dev code on strict mode and can reproduce the same issue. There are 2 toolbars instead of 1

**Comment by Noah-mh** [comment]
@VaguelySerious it could be because of the dynamic import, even tho i have "use client" in the page, there is client side error without dynamic import, it might also be because of nextjs as well.

**Comment by VaguelySerious** [comment]
Found the issue: React 18+ strict mode when using the new react-dom root creation syntax. This is now fixed in `react-quill-new@3.4.2`

**Comment by Dentling** [comment]
@VaguelySerious 
I am using React 19 and Version `react-quill-new@3.4.6` and still have the issue, when my App is wrapped in `<StrictMode>`.

When I remove the StrictMode, the toolbar only appears once but with the Strictmode it still appears 2 times.
Any idea?

**Comment by martinezguillaume** [comment]
Hello !
@VaguelySerious I have this issue too now ! When I remove StrictMode everything is working as expected !
```json
    "react-quill-new": "^3.4.6",
    "react": "^18.3.1",
```
